#!/usr/bin/env bash

fmt () {
    ocp-indent "$1" > tmp.ml
    if diff "$1" tmp.ml > /dev/null 2>&1; then
        rm tmp.ml
    else
        mv tmp.ml "$1"
    fi
}

fmt src/main.ml
ocaml -w +1..66 src/main.ml
